load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "67d6596d40b1807b9cd8eb0d9282932ea77be3c0",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:4068ab896a977849dec438d6616d0df0eea483c136bc546c5e4c107ef396fa53",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "vuejs/core",
    snapshot_id = "repository-snapshot-v1:3b5f437f41ce2dfe1328116a893b4cada05008f1210045630bef2ed1546038d3",
    source_tree_identity = "source-tree-js-ts-v1:c5681c6eeb4b34b1fba4085666bfddd431af60662eb27329dcf6826a00c22de6",
    visibility = ["//visibility:public"],
)
