load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "ebed8ea9f69216d3ce996dd88457046c0a033caf",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:c8aa6426628c069296fce8ea7282a0e928151f516b6915a6171b53f44bc1bb96",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:e340eb56a90c936d4a5879ec37f471260b07abeb021a11a29e2f3db0d1e35520",
    source_tree_identity = "source-tree-js-ts-v1:05fa6c316e581b5ca9f32ee3598aa17678df733eec331231c1d0f4851ee5ec63",
    visibility = ["//visibility:public"],
)
