load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "372720ec8bab38e33fa0c375ce231c67792f43a4",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:d6c3087503ab9b77c9f1bce7e25ec7a85a1f22d3367d099accc66f6505308e00",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "element-hq/element-web",
    snapshot_id = "repository-snapshot-v1:25054646c3f316d59634b7ef351e4cceae0e15c1ed4ad6e7b6a9e6ea07f4629f",
    source_tree_identity = "source-tree-js-ts-v1:fde423c9c8f7811d01a3db32b01dbbddf90ef7321c1f5d9bdd54d23ddcd39ad4",
    visibility = ["//visibility:public"],
)
