java_binary(
    name = "flix",
    main_class = "ca.uwaterloo.flix.Main",
    runtime_deps = ["@flix_compiler//jar"],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = [
        "//native/parquet:attune_parquet_test",
        "//test:core_parity_test",
    ],
)
