[package]
name        = "attuneflix"
description = "A small native Flix explanation of Attune Radii"
version     = "0.1.0"
flix        = "0.76.0"
authors     = ["Attune"]

[jar-dependencies]
"attune-grit.jar" = "url:file:.build/grit/attune-grit.jar"
"attune-nix.jar" = "url:file:.build/nix/attune-nix.jar"
"attune-embed.jar" = "url:file:.build/embed/attune-embed.jar"
