load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "c5ae8a70e1b0305af324ad7b1b0911d4023f1338",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:90c3880d0a14a60fb5206b84052873c376d954de7135ce1c6ad4fdda17612ad9",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:4b14c05228d2c59e68c2aaa978fb7d655aed032a75804f35ac94389520607084",
    source_tree_identity = "source-tree-js-ts-v1:153d2e096a79845e60747c9f2ec728f09b52a7667e198f18d3a82c4f15672f5b",
    visibility = ["//visibility:public"],
)
