load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "3653bc0f45d6fedf84e29b64ca52584359c383c0",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:853f845a8b5773684f37051bbe5db63336b43781ecd32e30a187ce914927c1a0",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "vuejs/core",
    snapshot_id = "repository-snapshot-v1:96c87d8880052c38779278f3f6da6b143c57f5f8fc252f529321c73fdfb32510",
    source_tree_identity = "source-tree-js-ts-v1:00417218678682b50e8ae6a5a31f98cb904284705c6cb8c1682b3c1cc37d5d8a",
    visibility = ["//visibility:public"],
)
