[package]
name = "attune-radii-grit"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "_attune_grit"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "=0.29.2"
features = ["extension-module", "abi3-py313"]

[dependencies.marzano-core]
git = "https://github.com/getgrit/gritql.git"
rev = "c80b3026471b229f41b279c3eb0c162dcdacfdb1"
package = "marzano-core"
default-features = false
features = [
    "grit-parser",
    "non_wasm",
]

[dependencies.marzano-language]
git = "https://github.com/getgrit/gritql.git"
rev = "c80b3026471b229f41b279c3eb0c162dcdacfdb1"
package = "marzano-language"
default-features = false
features = [
    "grit-parser",
    "tree-sitter-gritql",
    "tree-sitter-python",
    "tree-sitter-go",
    "tree-sitter-javascript",
    "tree-sitter-rust",
    "tree-sitter-java",
    "tree-sitter-php",
    "tree-sitter-typescript",
    "tree-sitter-ruby",
]

[dependencies.marzano-util]
git = "https://github.com/getgrit/gritql.git"
rev = "c80b3026471b229f41b279c3eb0c162dcdacfdb1"
package = "marzano-util"
