load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "a3e1a666b876e0b3ccbb5284dd826c8c90c113b4",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:0f72a530e24b54da102cb57736566b41367f4f0c45f8550a8aa4a1bc177d9466",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:8037ac6f92441b6ba2c9c85ca3cdd7f469430c8c1337a783b44985f6b180829e",
    source_tree_identity = "source-tree-js-ts-v1:e6cd9fd45eae2090016168d2c7e9b64bec45bc52fd1eb001f24975bc3d6e6ba5",
    visibility = ["//visibility:public"],
)
