load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "078178de4df1ffb606f1fc5a46bebe6c31d06b4a",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:c6413144d1548d8fa86ecbf156d7a29082286815d681a1e6b336fe6288a27833",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:accf5131f33552a6d04eff95d31291c1a10f47a2ac05b625004fd7e50da33881",
    source_tree_identity = "source-tree-js-ts-v1:e8be839e14f9e5edfd0e21a726552d37b489cb2d7bf75accf3b311dec25c10f8",
    visibility = ["//visibility:public"],
)
