load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "7ff95b70115415f47b89c81a40e90b60bcf3dbd8",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:38bcbadb83dff4ddd64d0084f4495da007c6c77f9b31cb3ec7262e9d358a046d",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:5186c9010641e075f7ffc0d7b0f0752b8260f64862e3e5e9f1ec6b592313844f",
    source_tree_identity = "source-tree-js-ts-v1:fe46578e5c9456a578ac1611939e28eb15f7fda37b04cb3cfca0e4c0ceedb834",
    visibility = ["//visibility:public"],
)
