load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "da2441b9bd293d7188ee645be3322a7305a43a19",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:d5263e45a5985280b3939a578d623818171817c6ef4f899250a8340c43fad4ee",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:0a4d2c8aacbbd3762bd6976bcf91866f819881ab0aad5580d9fadfdc6bbbd973",
    source_tree_identity = "source-tree-js-ts-v1:12bec1e3e5b251227101237d0ad32f02ae6775808ffaef6c7ff5f86950fb94b3",
    visibility = ["//visibility:public"],
)
