load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "19b81d257f7b8b134bf5d7e555c9d5fca3570f69",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:d79b58048b352b5f8b5c0731949cf1f0f9df5f8e48e9015bacf9d87ce2b48a88",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "element-hq/element-web",
    snapshot_id = "repository-snapshot-v1:be4b21ddb7b9f5c36b7d8004dee3a4592466219b32245d5d58b7e012b2a6bc8d",
    source_tree_identity = "source-tree-js-ts-v1:dcce945b70cb0747125adddb28d65f37f82cf1b335ccb3ba06bbb0c63c5a6b01",
    visibility = ["//visibility:public"],
)
