load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "3f9771dd682247118e66e9e27bc6ef677ef5214d",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:ec127e3a32f3562356f8a067db31b8923065e85a37a1b0fb899f388290e22c20",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:e87245df2ce6b98863e6644cf146b0cc6992c7a5fdce6a067b997b3e75004230",
    source_tree_identity = "source-tree-js-ts-v1:36f3bf73fb86d65a733f2f86d1ff24ea24140bbd1baa305a5d029f4bbeef177d",
    visibility = ["//visibility:public"],
)
