load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "c12331064f4ea967641cd5e419204422af050fbb",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:0163fcd6de94043cdad42f8f714f150fe4918044a67039203f900e396e95b682",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "preactjs/preact",
    snapshot_id = "repository-snapshot-v1:80b1792c54806b7f668cfe99126d221f59f280188794510cb57425a54dc9bf26",
    source_tree_identity = "source-tree-js-ts-v1:7f16ef9ccf4c526b5ae0a7e44a9a7de02a257a0ee4d07953659c42bfd26f39d2",
    visibility = ["//visibility:public"],
)
