load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "c40dccc34870418e29f51861a38647bc1cbdf0a8",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:30fdb32a1193739ec452da08c43736ad452a8f948c7f1c353773808a7534e277",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:2d1fa59b3248944c7ea360bc178a689cddf1fe733db9d3dca1e34529c1939157",
    source_tree_identity = "source-tree-js-ts-v1:c83ba18665a8b4087a30b85c348d5c67575ef726de871a6d5cdbf5d331c75bd1",
    visibility = ["//visibility:public"],
)
