load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "03a98f4de484f16d038892a0a9d2317a45e79df1",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:15b0460ef38b1d6b3ab27f31ab36079e4d0335ae838f61461f190d75b6410fbe",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:43d1969f5d5b33ddcee39867475aaf1fdde2042171e2425b339e9b2fbffb8e5a",
    source_tree_identity = "source-tree-js-ts-v1:2b3adcb04b56bbad79f57adec5b2b0ab33cbb8974e458b0f5c70b0fffad8b453",
    visibility = ["//visibility:public"],
)
