load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "212233cb0b9127c95966492175a730d5b954690f",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:4e7a2359d7e9ccaec2086305ca4655cb7f8843b12d1b83d85871ad5f4b5c750b",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "element-hq/element-web",
    snapshot_id = "repository-snapshot-v1:1f1fb6e8cbfb38f8d2f6f641fba3fbce89a1adfde8e9fd6b73cefd08611df23e",
    source_tree_identity = "source-tree-js-ts-v1:185d514ca227a647cdc5d8addce94942ecd573608fa9482d1dc88ceccdfebd44",
    visibility = ["//visibility:public"],
)
