load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "ab5e2a416324ec56cea44b79067ba798f8394de1",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:6e7ce65994d61cb0c1c6a41e5697651f801c746d4087f397690d95b026918e22",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:bb174a00f1122b9df7e4ebb958bbcad8e5bd9c1842bb8da9add37a00f034747d",
    source_tree_identity = "source-tree-js-ts-v1:757b33f8b94d434f5231ca82b29c29f2c7b428bee552004933eb510eb7aae11a",
    visibility = ["//visibility:public"],
)
