from pathlib import Path

class Column:
    @property
    def null_count(self) -> int: ...
    def unique(self) -> Column: ...
    def to_pylist(self) -> list[object]: ...

class Table:
    def column(self, name: str) -> Column: ...
    def to_pylist(self) -> list[dict[str, object]]: ...

class FileMetaData:
    @property
    def num_rows(self) -> int: ...

class Schema:
    @property
    def names(self) -> list[str]: ...

def read_table(
    source: Path,
    *,
    columns: list[str] | None = ...,
    filters: list[tuple[str, str, object]] | None = ...,
) -> Table: ...
def read_metadata(
    where: Path,
) -> FileMetaData: ...
def read_schema(
    where: Path,
) -> Schema: ...
