load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "a2ebf53b6098635c3abcab3fd9144c766e32b350",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:00cd91127f3840bfec4c6f665a938296e2d3d132d8ffe291bbaf1e58a3109e68",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:d81af495867cd7415488f697c081ce31ea2241c54bced4a8b496d67a894d2178",
    source_tree_identity = "source-tree-js-ts-v1:bd15564b5364d263c676e620437ffc94d46a26addd3aa78d92f6064a3bb53150",
    visibility = ["//visibility:public"],
)
