load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "5e9e1d051b2217b95498ecbc10f7e33f64e7a4d3",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:a2132e4be9e605824a6c71edffd739627598e1a680183063ce866d58c93e57b0",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "facebook/docusaurus",
    snapshot_id = "repository-snapshot-v1:b9dd309ede3789e905993b104f3d9ff206a8810300c413fc3d467bbb1c2a1780",
    source_tree_identity = "source-tree-js-ts-v1:4986fc15aab953453236f3366943bc3ba83b72ae42a2a9ba20703a5b2cf13f1f",
    visibility = ["//visibility:public"],
)
