load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "21b45bd4378834403ad9e69dc91605c21f43438b",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:96f7fe26bda4d24767bb7d091ff4807581369e4e8a2dc7db378fda43f3b6ffd0",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "protonmail/webclients",
    snapshot_id = "repository-snapshot-v1:0cc7b7c20b18e7bd7980c4510936b82c6d2a42556bbf86bacb56c23cfd87e6f1",
    source_tree_identity = "source-tree-js-ts-v1:34f99c2cfc2cfa0de9fa9f3d95fa53f1aafa7371f1601bee4a42f42c085de755",
    visibility = ["//visibility:public"],
)
