load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "3ecbb624d892b9fce078304cf89c0fe94f8ab3be",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:6fd5b3b0dbc9524a4250763bebfa72ff2423b4334c2610de462f8c751f00f5cf",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:55d7a8cefbffbce2fd6aed9ed500e8473d5dc49b8f9308f1eede358dd1593911",
    source_tree_identity = "source-tree-js-ts-v1:d86ab15cb09905c1246374db40f4a5c77b9364f90066b096af3bde281bd53cc4",
    visibility = ["//visibility:public"],
)
