load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "26c98dd37701c1c657edec33465d52e43e4a05cb",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:488da61c17d8aca193b0ff3d99c77858819f1f0976197c293264b984f7654608",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "tutao/tutanota",
    snapshot_id = "repository-snapshot-v1:45b8021a93812ab4080edeb1f8ebfcb1acad5ffe4d6d7122a30179a7e409c578",
    source_tree_identity = "source-tree-js-ts-v1:071705d26d45ce3a08691f7dc4f9a3b4755ea97562cf4b704ab31fc0b1404110",
    visibility = ["//visibility:public"],
)
