load("//build:attune.bzl", "attune_world_files")

attune_world_files(
    name = "world",
    base_revision = "163c977d2f4891fa7c4372b9f6a686b1fa34350f",
    entities = "entities.parquet",
    fact_identity = "repository-facts-v2:248b0ff30bfc510a397b82bea6030e911ebda6b1d1ba9cf253800248f187788f",
    identity = "identity.json",
    metadata = "metadata.parquet",
    relations = "relations.parquet",
    repository = "NodeBB/NodeBB",
    snapshot_id = "repository-snapshot-v1:c39f4787c4aad99b5033c759a3a9acb952f98d199b06d58ffdb231f058760d4e",
    source_tree_identity = "source-tree-js-ts-v1:dab433d08b3f7b57ba41e854c4d0705118de859b83402bcce49dd1d5d9fb5962",
    visibility = ["//visibility:public"],
)
